version: '3'
services:
  dynamodb:
    image: tray/dynamodb-local
    ports:
      - "7777:7777"
    command: "-inMemory -port 7777"
  elasticsearch:
    image: elasticsearch:6.8.13
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"