version: 2
defaults: &defaults
    docker:
      - image: circleci/python:2.7-stretch-browsers
install_dependency: &install_dependency
  name: Installation of build and deployment dependencies.
  command: |
    sudo apt install jq
    sudo pip install awscli --upgrade
    sudo pip install docker-compose
install_deploysuite: &install_deploysuite
  name: Installation of install_deploysuite.
  command: |
    git clone --branch v1.4 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
    cp ./../buildscript/master_deploy.sh .
    cp ./../buildscript/buildenv.sh .
    cp ./../buildscript/awsconfiguration.sh .
restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-{{ checksum "package-lock.json" }}

save_cache_settings: &save_cache_settings
  key: docker-node-modules-{{ checksum "package-lock.json" }}
  paths:
    - node_modules

builddeploy_steps: &builddeploy_steps
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - restore_cache: *restore_cache_settings_for_build
      - run: ./build.sh ${APPNAME}
      - save_cache: *save_cache_settings
      - deploy:
          name: Running MasterScript.
          command: |
            ./awsconfiguration.sh $DEPLOY_ENV
            source awsenvconf
            ./buildenv.sh -e $DEPLOY_ENV -b ${LOGICAL_ENV}-${APPNAME}-deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e $DEPLOY_ENV -t latest -s ${LOGICAL_ENV}-global-appvar,${LOGICAL_ENV}-${APPNAME}-appvar -i ${APPNAME}


jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    environment:
      DEPLOY_ENV: "DEV"
      LOGICAL_ENV: "dev"
      APPNAME: "resources-api"    
    steps: *builddeploy_steps

  "build-prod":
    <<: *defaults
    environment:
      DEPLOY_ENV: "PROD"
      LOGICAL_ENV: "prod"    
      APPNAME: "resources-api"  
    steps: *builddeploy_steps

  "Run-Newman-Test":
    docker:
      - image: circleci/node:12
      - image: tray/dynamodb-local
        command: "-inMemory -port 7777"
      - image: elasticsearch:6.8.13
        environment:
          discovery.type: "single-node"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'newman test'
          command: |
            npm i
            cd local
            cd ..
            npm run create-tables:test
            cd mock
            (npm run mock-challenge-api&)
            (NODE_ENV=test npm start&)
            npm run test:newman    

workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only:
                - develop

      # Production builds are exectuted only on tagged commits to the
      # master branch.
      - "build-prod":
          context : org-global
          filters:
            branches:
              only: master

      - "Run-Newman-Test":
          context : org-global
          requires:
            - build-dev
            - build-prod          
          filters:
            branches:
              only:
                - automated-postman-testing
                - develop